### ISSUE TITLE
Transportadoras não adicionadas

### ISSUE THREAD

**Issue by lucasferreiraestevam** [FrenetGatewaydeFretes/frenet_prestashop#1]
Configurações realizadas mas após salvar as transportadoras não são adicionadas na loja.

Prestashop v 1.6.1.23

**Comment by dubaggio** [comment]
Olá Lucas,

Sempre que precisar de suporte técnico envie um e-mail para suporte@frenet.com.br

Vi que você já entrou em contato com o nosso time de suporte e eles já estão analisando o seu caso.

Assim que eles obtiverem uma resposta eles irão comunica-lo.
