### ISSUE TITLE
Atualização requerida

### ISSUE THREAD

**Issue by matheusbach** [FrenetGatewaydeFretes/frenet_prestashop#12]
O módulo não funciona mais adequadamente no prestashop 1.7.x

Poderam atualizar módulo para continuar sendo possível usar?

**Comment by alexandercamps** [comment]
Bom dia @matheusbach !
Realizei testes com as ultimas versão do Prestashop 8.0.4 e1.7.8.9 , o módulo se comportou como o esperado.

Ultimas versões:
8.0.4: https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.4
1.7.8.9: https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.9

Poderia compartilhar mais informações sobre o problema?

Abs,
